#import "../Cocktail/BasicCocktailDetails.gql"

query DislikedCocktails($first: Int!, $after: String) {
  dislikedCocktails(first: $first, after: $after) {
    pageInfo {
      endCursor
      hasNextPage
    }
    cocktails {
      ...BasicCocktailDetails
    }
  }
}
